### ISSUE TITLE
Chose a Color Palette 

### ISSUE THREAD

**Issue by Cristiano-Fazi** [carsonSgit/TradeMind#10]
### Task Description
Chose an appropriate color palette for the app.

### Additional Context
Just pick a good one

**Comment by carsonSgit** [comment]
|Colour         | Hex |
|----------------|----------|
| Black          | #000000  |
| White          | #FFFFFF  |
| Grey           | #CDCDCD  |
| Light Purple   | #673AB7  |
| Dark Purple    | #522E93  |
| Blue Purple    | #443A90 |
